---

-   name: Install Docker
    yum: name=docker state=latest
    tags: docker

-   name: Make sure Docker is running
    service: name=docker state=running
    tags: docker

- name: Run Jenkins master container
  docker_container:
    name: jenkins
    image: jenkins
    published_ports:
      - "8080:8080"
      - "50000:50000"
    env:
      jenkins_home: /var/jslaves-config
